### ISSUE TITLE
can't start ukraine

### ISSUE THREAD

**Issue by modestemax** [radekstepan/ukraine#55]
i have this when i try to start ukraine
max opt # ukraine 
debug:   Loading config
debug:   Loading router
info:    Welcome to ukraine comrade
help:           __             _  
help:     __ **/ /** _______ _(_)__  ___ 
help:    / // /  '_// __/ _ `/ / _ \/ -_)
help:    \_,_/_/_\/_/  \_,_/_/_//_/__/ 
help:  
help:    Management of Node.js cloud apps
help:  
debug:   Checking version of Node.js
error:   Node.js v0.8.x is allowed only, not v0.10.18

**Comment by radekstepan** [comment]
Will remove the check now that it is working. Will also upgrade my version to 0.10.18 as per yours.

**Comment by radekstepan** [comment]
Can you check now?

**Comment by modestemax** [comment]
thanks it works
