### ISSUE TITLE
can't deploy app with chernobyl

### ISSUE THREAD

**Issue by modestemax** [radekstepan/ukraine#56]
sorry for disturbing,
after successfully setup and launch ukraine, it's time to deploy an app.
i have the following  error when trying.

max bin # chernobyl deploy 127.0.0.1
info:    Welcome to chernobyl comrade
help:          __                     __        __
help:     ____/ /  ___ _______  ___  / /  __ **/ /
help:    / __/ _ \/ -_) __/ _ \/ _ \/ _ \/ // / / 
help:    \**/_//_/__/_/ /_//_/_**/_.**/_, /_/  
help:                                   /___/  
help:  
help:    Deployment of Node.js cloud apps
help:  
info:    Executing the deploy command
debug:   Attempting to read package.json file
error:   ENOENT, open 'undefined/package.json'

**Comment by radekstepan** [comment]
Hi, try like this:

`chernobyl deploy <path to ukraine host> <local path to your app>`

**Comment by modestemax** [comment]
here you have the new error

---

max example_app # chernobyl deploy 127.0.0.1 .
info:    Welcome to chernobyl comrade
help:          __                     __        __
help:     ____/ /  ___ _______  ___  / /  __ **/ /
help:    / __/ _ \/ -_) __/ _ \/ _ \/ _ \/ // / / 
help:    \**/_//_/__/_/ /_//_/_**/_.**/_, /_/  
help:                                   /___/  
help:  
help:    Deployment of Node.js cloud apps
help:  
info:    Executing the deploy command
debug:   Attempting to read package.json file
debug:   Attempting to parse package.json file
debug:   Checking for app field in package.json file
debug:   Checking for scripts field in package.json file
debug:   Is haibu up?
debug:   Getting haibu version
info:    haibu 0.9.8 accepting connections
debug:   Sending example-app to haibu
debug:   Is app running already?
debug:   Deploying app
warn:    Attempting to cleanup chernobyl/example-app if exists
debug:   Copying app to /usr/lib/node_modules/ukraine/node_modules/haibu/local/chernobyl/example-app
warn:    The app chernobyl/example-app exists already
debug:   Trying to install dependencies for /usr/lib/node_modules/ukraine/node_modules/haibu/local/chernobyl/example-app
express@2.5.11 ../../../../../usr/lib/node_modules/ukraine/node_modules/haibu/local/chernobyl/example-app/chernobyl-example-app-1379954069998/node_modules/express
├── qs@0.4.2
├── mime@1.2.4
├── mkdirp@0.3.0
└── connect@1.9.2 (formidable@1.0.14)
debug:   Attempting to spawn chernobyl/example-app
error:   Error spawning drone

**Comment by radekstepan** [comment]
Hmm, look at `/server/logs/`. One of the reasons for requiring `0.8.x` of node was to avoid problems like these. It throws:

`No appropiate net override for node version v0.10.18`

This seems like a non-trivial fix and I won't probably have time to fix it in in a near future (about two weeks). If you'd like a fix I'd go through the source of `haibu-carapace` in `node_modules` and see what gives.

**Comment by radekstepan** [comment]
OK that is fixed for me now. You need to re-install `ukraine` or its deps.

**Comment by modestemax** [comment]
tank you it works
